import { AppTheme } from '../types';

export interface ThemeOption {
  id: AppTheme;
  nameEn: string;
  nameAr: string;
  sloganEn: string;
  sloganAr: string;
  vibeEn: string;
  vibeAr: string;
  primaryColor: string;
  bgPreview: string;
  cardPreview: string;
  textColor: string;
  borderPreview: string;
  iconName: string;
  badge: string;
  badgeAr: string;
}

export const THEME_OPTIONS: ThemeOption[] = [
  {
    id: 'fitness_dark',
    nameEn: 'Emerald Beast',
    nameAr: 'الزمرد الرياضي (Beast)',
    sloganEn: 'High-contrast neon emerald for ruthless consistency.',
    sloganAr: 'أخضر نيون متباين لعزيمة وانضباط حديدي لا يلين.',
    vibeEn: 'Beast Mode & Hypertrophy',
    vibeAr: 'وضع الوحش وتضخيم العضلات',
    primaryColor: '#10b981',
    bgPreview: '#080d0a',
    cardPreview: '#0f1813',
    textColor: '#f0fdf4',
    borderPreview: '#1e382b',
    iconName: 'Zap',
    badge: 'BEAST MODE',
    badgeAr: 'وضع الوحش',
  },
  {
    id: 'volcanic_red',
    nameEn: 'Volcanic PR',
    nameAr: 'اللهب البركاني (PR Flame)',
    sloganEn: 'Explosive crimson blaze for heavy lifting PRs.',
    sloganAr: 'لهب أحمر متفجر لتحطيم الأرقام القياسية في الأوزان.',
    vibeEn: 'Max Adrenaline & Power',
    vibeAr: 'أقصى أدرينالين وقوة انفجارية',
    primaryColor: '#f43f5e',
    bgPreview: '#0d0708',
    cardPreview: '#170d10',
    textColor: '#fff1f2',
    borderPreview: '#381822',
    iconName: 'Flame',
    badge: 'PR ADRENALINE',
    badgeAr: 'أرقام قياسية',
  },
  {
    id: 'electric_cyan',
    nameEn: 'Cyber Cyan',
    nameAr: 'السايبر النيون (Cyber Cyan)',
    sloganEn: 'Futuristic electric cyan for high-tech athletic precision.',
    sloganAr: 'أزرق سماوي كهربائي لدقة رياضية عالية وتكنيك احترافي.',
    vibeEn: 'Cyber Stealth & Biomechanics',
    vibeAr: 'سايبر وتكنيك بيوميكانيكي',
    primaryColor: '#06b6d4',
    bgPreview: '#060e14',
    cardPreview: '#0b1824',
    textColor: '#ecfeff',
    borderPreview: '#163654',
    iconName: 'Cpu',
    badge: 'CYBER PRECISION',
    badgeAr: 'دقة سايبر',
  },
  {
    id: 'cyber_lime',
    nameEn: 'Kinetic Lime',
    nameAr: 'الليموني الحركي (Kinetic Fuel)',
    sloganEn: 'High-voltage acid lime for explosive stamina and drive.',
    sloganAr: 'طاقة نيون حركية للياقة عالية ونشاط تدريبي مكثف.',
    vibeEn: 'High Kinetic Fuel',
    vibeAr: 'وقود حركي عالي الكثافة',
    primaryColor: '#84cc16',
    bgPreview: '#070e06',
    cardPreview: '#0e1d0d',
    textColor: '#f7fee7',
    borderPreview: '#24461f',
    iconName: 'Activity',
    badge: 'ENDURANCE DRIVE',
    badgeAr: 'طاقة حركية',
  },
  {
    id: 'spartan_gold',
    nameEn: 'Spartan Gold',
    nameAr: 'الذهب الإسبارطي (Victory Arena)',
    sloganEn: 'Lustrous trophy gold inspired by championship discipline.',
    sloganAr: 'بريق الذهب الملكي المستوحى من عقلية الأبطال والانضباط الصارم.',
    vibeEn: 'Championship Victory Mindset',
    vibeAr: 'عقلية البطولة والمجد',
    primaryColor: '#eab308',
    bgPreview: '#0d0a06',
    cardPreview: '#19140a',
    textColor: '#fefce8',
    borderPreview: '#3d2f16',
    iconName: 'Crown',
    badge: 'CHAMPION STATUS',
    badgeAr: 'روح البطولة',
  },
  {
    id: 'solar_orange',
    nameEn: 'Solar Blaze',
    nameAr: 'التوهج الشمسي (Solar Ignite)',
    sloganEn: 'Radiant solar energy to incinerate fat & accelerate metabolism.',
    sloganAr: 'طاقة شمسية ملتهبة لحرق الدهون وزيادة معدل الأيض.',
    vibeEn: 'Metabolic Fat Incineration',
    vibeAr: 'حرق واستشفاء نشط',
    primaryColor: '#f97316',
    bgPreview: '#0e0805',
    cardPreview: '#1a100a',
    textColor: '#fff7ed',
    borderPreview: '#3d2417',
    iconName: 'SunMedium',
    badge: 'METABOLIC IGNITE',
    badgeAr: 'حرق مكثف',
  },
  {
    id: 'royal_violet',
    nameEn: 'Apex Violet',
    nameAr: 'قمة التركيز (Apex Flow)',
    sloganEn: 'Deep ultraviolet void for laser-focused flow state.',
    sloganAr: 'بنفسجي ملكي هادئ لحالة تركيز عميقة وفصل الذهن عن كل مشتت.',
    vibeEn: 'Deep Focus & Flow State',
    vibeAr: 'تركيز عميق وصفاء ذهني',
    primaryColor: '#a855f7',
    bgPreview: '#090611',
    cardPreview: '#140d24',
    textColor: '#faf5ff',
    borderPreview: '#311c58',
    iconName: 'Sparkles',
    badge: 'FLOW STATE',
    badgeAr: 'قمة التركيز',
  },
  {
    id: 'arctic_frost',
    nameEn: 'Arctic Frost',
    nameAr: 'الجليد التيتانيومي (Titanium Ice)',
    sloganEn: 'Glacial ice & titanium for cool composure and relentless reps.',
    sloganAr: 'أزرق ثلجي تيتانيومي لصفاء العقل وثبات الأداء تحت الضغط.',
    vibeEn: 'Stoic Discipline & Recovery',
    vibeAr: 'هدوء وانضباط ستويكي',
    primaryColor: '#38bdf8',
    bgPreview: '#060b11',
    cardPreview: '#0c1622',
    textColor: '#f0f9ff',
    borderPreview: '#18314e',
    iconName: 'Shield',
    badge: 'STOIC CLARITY',
    badgeAr: 'انضباط بارد',
  },
  {
    id: 'warm_amber',
    nameEn: 'Warm Amber',
    nameAr: 'الجمر الدافئ (Core Fire)',
    sloganEn: 'Warm embers and mahogany for grounded intensity.',
    sloganAr: 'دفء الخشب والجمر لقوة كامنة وأساس عضلي متين.',
    vibeEn: 'Core Fire & Grounded Grit',
    vibeAr: 'قوة أساسية راسخة',
    primaryColor: '#f59e0b',
    bgPreview: '#14100c',
    cardPreview: '#201a14',
    textColor: '#faf5f0',
    borderPreview: '#3d3227',
    iconName: 'Flame',
    badge: 'CORE FIRE',
    badgeAr: 'جمر القوة',
  },
  {
    id: 'elegant_dark',
    nameEn: 'Obsidian Indigo',
    nameAr: 'السواد الأنيق (Obsidian Indigo)',
    sloganEn: 'Sleek luxury dark mode with refined indigo accents.',
    sloganAr: 'مظهر داكن فاخر بلمسات زرقاء نيلية أنيقة ومريحة للعين.',
    vibeEn: 'Luxury Stealth & Modern UI',
    vibeAr: 'أناقة وفخامة حديثة',
    primaryColor: '#6366f1',
    bgPreview: '#0a0a0c',
    cardPreview: '#111115',
    textColor: '#e0e0e0',
    borderPreview: '#232330',
    iconName: 'Moon',
    badge: 'STEALTH LUXURY',
    badgeAr: 'سواد فاخر',
  },
  {
    id: 'dark',
    nameEn: 'Midnight Stealth',
    nameAr: 'منتصف الليل (Pure Carbon)',
    sloganEn: 'Minimalist stealth dark mode for nighttime training.',
    sloganAr: 'وضع داكن هادئ ومريح للعين أثناء جلسات التدريب الليلية.',
    vibeEn: 'Minimal Carbon Stealth',
    vibeAr: 'كربون نقي هادئ',
    primaryColor: '#6366f1',
    bgPreview: '#0b0f17',
    cardPreview: '#111827',
    textColor: '#f3f4f6',
    borderPreview: '#374151',
    iconName: 'Moon',
    badge: 'MINIMAL STEALTH',
    badgeAr: 'بسيط وهادئ',
  },
  {
    id: 'light',
    nameEn: 'Clean Light',
    nameAr: 'الضوء النقي (Daylight Focus)',
    sloganEn: 'High clarity daytime theme with crisp emerald contrast.',
    sloganAr: 'مظهر نهاري مشرق وعالي الوضوح مناسب للتدريب في الصباح أو الخارج.',
    vibeEn: 'Daylight Clarity & Energy',
    vibeAr: 'وضوح وطاقة نهارية',
    primaryColor: '#059669',
    bgPreview: '#f8fafc',
    cardPreview: '#ffffff',
    textColor: '#0f172a',
    borderPreview: '#e2e8f0',
    iconName: 'Sun',
    badge: 'DAYLIGHT CLARITY',
    badgeAr: 'وضوح نهاري',
  },
];
